export enum AppState {
    LANDING = "LANDING",
    INTRODUCTION = "INTRODUCTION",
    AGREEMENT = "AGREEMENT",
    DASHBOARD = "DASHBOARD",
    HALO_AUTH = "HALO_AUTH",
    TODOIST_AUTH = "TODOIST_AUTH",
    TODOIST_ERROR = "TODOIST_ERROR",
    TODOIST_SUCCESS = "TODOIST_SUCCESS",
}